### ISSUE TITLE
📰 Publish to pypi

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-py#71]
so we can reach more users!

also so cristi can use for testing

**Comment by izzylys** [comment]
did a dry run of this and works as expected! ready to do this pending a discussion on _how_ we want to do this given that 1.0 still needs to be available

1. if we want to risk of for the biscuit (ahem this was dim's suggestion so @ him) we can publish it as "speckle". however, we will need to start at version 2.4 because pypi won't let you rewrite old versions even if you delete them. this is confusing imo and will be confusing to people updating speckle
2. we rename this proj to `specklepy`, `speckle2`, `speckle-sdk` etc. can vote on this name!

**Comment by hubert-associates** [comment]
Hi Izzy, I ran in to this since I wanted to use your new WIP addin for blender ... which requires the new speckle-py, which only runs with poetry (propably)... I'm more a C#, so although I have the speckly-py local, I have no idea how to get the blender addin to use the new module with speckle.api. So a beta-package in pypi would help, or a hint how to make it available locally (these is no setup.py in the repo...) and never used poetry in py yet. For what its worth... Thx!

bpy.context.space_data.system_folders_active = 1
Traceback (most recent call last):
  File "D:\_rht_local\bin\Blender\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\_rht_local\bin\Blender\2.92\scripts\addons\bpy_speckle\__init__.py", line 56, in <module>
    from speckle.api.client import SpeckleClient  # , SpeckleCache
ModuleNotFoundError: No module named 'speckle.api'

Traceback (most recent call last):
  File "D:\_rht_local\bin\Blender\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "D:\_rht_local\bin\Blender\2.92\scripts\addons\bpy_speckle\__init__.py", line 56, in <module>
    from speckle.api.client import SpeckleClient  # , SpeckleCache
ModuleNotFoundError: No module named 'speckle.api'

**Comment by izzylys** [comment]
Heya, glad you're interested in trying the blender addon!

Sorry for the delay in closing this issue - there were some small issues we needed to iron out but I should be publishing it within the next couple of days so stay tuned! If you're desperate to try out blender stuff asap, for now you can just drop the `speckle` folder from this repo into `%APPDATA%\Blender Foundation\Blender\2.92\scripts\addons\modules` along with any other dependencies.

**Comment by izzylys** [comment]
hey @hubert-associates !

quick update for ya: you can now `pip install specklepy`! the package has been renamed `specklepy` so any scripts you have already referencing `speckle` will need to be updated.

the Blender addon hasn't been updated yet so you'll need to wait a bit on that, but there is a standing PR that will be merged as soon as it has been reviewed by the other main contributor.
