### ISSUE TITLE
🧪 Use docker image to spin up server for tests

### ISSUE THREAD

**Issue by izzylys** [specklesystems/speckle-py#79]
Due to server complications, tests using the server all fail. This change will make local testing more difficult, but make testing more robust in general.

Same as specklesystems/speckle-sharp#374

**Comment by AlanRynne** [comment]
This is done! Pending Izzy's fix to the failing tests to ensure everything runs smoothly.

**Comment by gjedlicska** [comment]
Hey all,
this sure works well with CI, but running the tests locally assumes you have a server up and running. Which should not be a mandatory thing IMHO.
This to me makes this problem a config thing.
If you are ok with it, I can make fix for this with [dynaconf](https://www.dynaconf.com/).

**Comment by didimitrie** [comment]
Hey @gjedlicska, we've discussed this internally, and for our workflows we said it's mostly fine like this. We've moved the .NET integration tests to do the same. Our solution to running integration tests locally, if one is too lazy to have a local server running, is to just push a commit and let the CI run them for you. Did you have an easier solution in mind? 

@AlanRynne & @izzylys, tests don't need to be fixed beforehand, that's not really related to this issue.

**Comment by gjedlicska** [comment]
Not really @didimitrie,
having a local server for testing is fine (this is what I ended up doing, since the tests were failing with the main branch pointing to latest.speckle.dev)
Its a bit inconvenient tough cause for specklepy, almost all tests are integration tests ATM, plus the server access should be configurable from env vars in the long run, with sensible defaults.

Describing the solution is a bit more lengthy than doing a POC, because of how convenient using Dynaconf is.
My idea is something along the lines of this:
https://www.dynaconf.com/advanced/#a-python-program

**Comment by didimitrie** [comment]
Having an env var to configure the testing server's url is not a bad thing to have, with a sensible default to localhost. This is for another PR later though, for now the priority is to have these tests run against an always fresh, latest-latest server version :) If it becomes annoying we'll consider it. @AlanRynne or @izzylys will merge #82, but we can keep the conversation going if needed here.

**Comment by gjedlicska** [comment]
Ohh sorry, I did not raise this, to block the PR merge. My bad...
